package cn.sportsdata.webapp.youth.common.vo.patient;

import java.util.Date;

public class MedicalRecordVO {

    private String id;
    private String patientId;
    private Date visitDate;
    private Integer visitNo;
    private String anamnesis;
    private String familyIll;
    private String marrital;
    private String individual;
    private String menses;
    private String doctor;
    private Integer ordinal;
    private String doctorNo;
    private String tooth;
    private String memo;
    private String cdiag;
    private Date illnessDate;
    private String maternity;
    private Integer cfzFlag;
    private String menses2;
    private String menses3;
    private String menses4;
    private String assistantExam;
    private String diagYbDb;
    private String ybIcdName;
    private String hospitalId;
    private String status;
    private String illnessDesc;
    private String medHistory;
    private String bodyExam;
    private String diagDesc;
    private String treatment;
    private String suggestion;
    private String advice;
    private String operationRecord;
    private String medicalRecord;
    
    private String realName;
    private Date birthday;
    
    private String identityCard;
    
    private String phoneNumber;
    
    private String gender;
  
    private String name;
    
    private String accExam;

    public Date getBirthday() {
		return birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhoneNumber() {
		return phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getRealName() {
		return realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	public String getIdentityCard() {
		return identityCard;
	}

	public void setIdentityCard(String identityCard) {
		this.identityCard = identityCard;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.id
     *
     * @return the value of medical_record.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.id
     *
     * @param id the value for medical_record.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.PATIENT_ID
     *
     * @return the value of medical_record.PATIENT_ID
     *
     * @mbggenerated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.PATIENT_ID
     *
     * @param patientId the value for medical_record.PATIENT_ID
     *
     * @mbggenerated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.VISIT_DATE
     *
     * @return the value of medical_record.VISIT_DATE
     *
     * @mbggenerated
     */
    public Date getVisitDate() {
        return visitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.VISIT_DATE
     *
     * @param visitDate the value for medical_record.VISIT_DATE
     *
     * @mbggenerated
     */
    public void setVisitDate(Date visitDate) {
        this.visitDate = visitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.VISIT_NO
     *
     * @return the value of medical_record.VISIT_NO
     *
     * @mbggenerated
     */
    public Integer getVisitNo() {
        return visitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.VISIT_NO
     *
     * @param visitNo the value for medical_record.VISIT_NO
     *
     * @mbggenerated
     */
    public void setVisitNo(Integer visitNo) {
        this.visitNo = visitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.ANAMNESIS
     *
     * @return the value of medical_record.ANAMNESIS
     *
     * @mbggenerated
     */
    public String getAnamnesis() {
        return anamnesis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.ANAMNESIS
     *
     * @param anamnesis the value for medical_record.ANAMNESIS
     *
     * @mbggenerated
     */
    public void setAnamnesis(String anamnesis) {
        this.anamnesis = anamnesis == null ? null : anamnesis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.FAMILY_ILL
     *
     * @return the value of medical_record.FAMILY_ILL
     *
     * @mbggenerated
     */
    public String getFamilyIll() {
        return familyIll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.FAMILY_ILL
     *
     * @param familyIll the value for medical_record.FAMILY_ILL
     *
     * @mbggenerated
     */
    public void setFamilyIll(String familyIll) {
        this.familyIll = familyIll == null ? null : familyIll.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.MARRITAL
     *
     * @return the value of medical_record.MARRITAL
     *
     * @mbggenerated
     */
    public String getMarrital() {
        return marrital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.MARRITAL
     *
     * @param marrital the value for medical_record.MARRITAL
     *
     * @mbggenerated
     */
    public void setMarrital(String marrital) {
        this.marrital = marrital == null ? null : marrital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.INDIVIDUAL
     *
     * @return the value of medical_record.INDIVIDUAL
     *
     * @mbggenerated
     */
    public String getIndividual() {
        return individual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.INDIVIDUAL
     *
     * @param individual the value for medical_record.INDIVIDUAL
     *
     * @mbggenerated
     */
    public void setIndividual(String individual) {
        this.individual = individual == null ? null : individual.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.MENSES
     *
     * @return the value of medical_record.MENSES
     *
     * @mbggenerated
     */
    public String getMenses() {
        return menses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.MENSES
     *
     * @param menses the value for medical_record.MENSES
     *
     * @mbggenerated
     */
    public void setMenses(String menses) {
        this.menses = menses == null ? null : menses.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.DOCTOR
     *
     * @return the value of medical_record.DOCTOR
     *
     * @mbggenerated
     */
    public String getDoctor() {
        return doctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.DOCTOR
     *
     * @param doctor the value for medical_record.DOCTOR
     *
     * @mbggenerated
     */
    public void setDoctor(String doctor) {
        this.doctor = doctor == null ? null : doctor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.ORDINAL
     *
     * @return the value of medical_record.ORDINAL
     *
     * @mbggenerated
     */
    public Integer getOrdinal() {
        return ordinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.ORDINAL
     *
     * @param ordinal the value for medical_record.ORDINAL
     *
     * @mbggenerated
     */
    public void setOrdinal(Integer ordinal) {
        this.ordinal = ordinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.DOCTOR_NO
     *
     * @return the value of medical_record.DOCTOR_NO
     *
     * @mbggenerated
     */
    public String getDoctorNo() {
        return doctorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.DOCTOR_NO
     *
     * @param doctorNo the value for medical_record.DOCTOR_NO
     *
     * @mbggenerated
     */
    public void setDoctorNo(String doctorNo) {
        this.doctorNo = doctorNo == null ? null : doctorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.TOOTH
     *
     * @return the value of medical_record.TOOTH
     *
     * @mbggenerated
     */
    public String getTooth() {
        return tooth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.TOOTH
     *
     * @param tooth the value for medical_record.TOOTH
     *
     * @mbggenerated
     */
    public void setTooth(String tooth) {
        this.tooth = tooth == null ? null : tooth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.MEMO
     *
     * @return the value of medical_record.MEMO
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.MEMO
     *
     * @param memo the value for medical_record.MEMO
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.CDIAG
     *
     * @return the value of medical_record.CDIAG
     *
     * @mbggenerated
     */
    public String getCdiag() {
        return cdiag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.CDIAG
     *
     * @param cdiag the value for medical_record.CDIAG
     *
     * @mbggenerated
     */
    public void setCdiag(String cdiag) {
        this.cdiag = cdiag == null ? null : cdiag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.ILLNESS_DATE
     *
     * @return the value of medical_record.ILLNESS_DATE
     *
     * @mbggenerated
     */
    public Date getIllnessDate() {
        return illnessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.ILLNESS_DATE
     *
     * @param illnessDate the value for medical_record.ILLNESS_DATE
     *
     * @mbggenerated
     */
    public void setIllnessDate(Date illnessDate) {
        this.illnessDate = illnessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.MATERNITY
     *
     * @return the value of medical_record.MATERNITY
     *
     * @mbggenerated
     */
    public String getMaternity() {
        return maternity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.MATERNITY
     *
     * @param maternity the value for medical_record.MATERNITY
     *
     * @mbggenerated
     */
    public void setMaternity(String maternity) {
        this.maternity = maternity == null ? null : maternity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.CFZ_FLAG
     *
     * @return the value of medical_record.CFZ_FLAG
     *
     * @mbggenerated
     */
    public Integer getCfzFlag() {
        return cfzFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.CFZ_FLAG
     *
     * @param cfzFlag the value for medical_record.CFZ_FLAG
     *
     * @mbggenerated
     */
    public void setCfzFlag(Integer cfzFlag) {
        this.cfzFlag = cfzFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.MENSES2
     *
     * @return the value of medical_record.MENSES2
     *
     * @mbggenerated
     */
    public String getMenses2() {
        return menses2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.MENSES2
     *
     * @param menses2 the value for medical_record.MENSES2
     *
     * @mbggenerated
     */
    public void setMenses2(String menses2) {
        this.menses2 = menses2 == null ? null : menses2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.MENSES3
     *
     * @return the value of medical_record.MENSES3
     *
     * @mbggenerated
     */
    public String getMenses3() {
        return menses3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.MENSES3
     *
     * @param menses3 the value for medical_record.MENSES3
     *
     * @mbggenerated
     */
    public void setMenses3(String menses3) {
        this.menses3 = menses3 == null ? null : menses3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.MENSES4
     *
     * @return the value of medical_record.MENSES4
     *
     * @mbggenerated
     */
    public String getMenses4() {
        return menses4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.MENSES4
     *
     * @param menses4 the value for medical_record.MENSES4
     *
     * @mbggenerated
     */
    public void setMenses4(String menses4) {
        this.menses4 = menses4 == null ? null : menses4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.ASSISTANT_EXAM
     *
     * @return the value of medical_record.ASSISTANT_EXAM
     *
     * @mbggenerated
     */
    public String getAssistantExam() {
        return assistantExam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.ASSISTANT_EXAM
     *
     * @param assistantExam the value for medical_record.ASSISTANT_EXAM
     *
     * @mbggenerated
     */
    public void setAssistantExam(String assistantExam) {
        this.assistantExam = assistantExam == null ? null : assistantExam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.DIAG_YB_DB
     *
     * @return the value of medical_record.DIAG_YB_DB
     *
     * @mbggenerated
     */
    public String getDiagYbDb() {
        return diagYbDb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.DIAG_YB_DB
     *
     * @param diagYbDb the value for medical_record.DIAG_YB_DB
     *
     * @mbggenerated
     */
    public void setDiagYbDb(String diagYbDb) {
        this.diagYbDb = diagYbDb == null ? null : diagYbDb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.YB_ICD_NAME
     *
     * @return the value of medical_record.YB_ICD_NAME
     *
     * @mbggenerated
     */
    public String getYbIcdName() {
        return ybIcdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.YB_ICD_NAME
     *
     * @param ybIcdName the value for medical_record.YB_ICD_NAME
     *
     * @mbggenerated
     */
    public void setYbIcdName(String ybIcdName) {
        this.ybIcdName = ybIcdName == null ? null : ybIcdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.HOSPITAL_ID
     *
     * @return the value of medical_record.HOSPITAL_ID
     *
     * @mbggenerated
     */
    public String getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.HOSPITAL_ID
     *
     * @param hospitalId the value for medical_record.HOSPITAL_ID
     *
     * @mbggenerated
     */
    public void setHospitalId(String hospitalId) {
        this.hospitalId = hospitalId == null ? null : hospitalId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.STATUS
     *
     * @return the value of medical_record.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.STATUS
     *
     * @param status the value for medical_record.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
    
    
    private String patient_name;
	public String getPatient_name() {
		return patient_name;
	}

	public void setPatient_name(String patient_name) {
		this.patient_name = patient_name;
	}

	public String getIllnessDesc() {
		return illnessDesc;
	}

	public void setIllnessDesc(String illnessDesc) {
		this.illnessDesc = illnessDesc;
	}

	public String getMedHistory() {
		return medHistory;
	}

	public void setMedHistory(String medHistory) {
		this.medHistory = medHistory;
	}

	public String getBodyExam() {
		return bodyExam;
	}

	public void setBodyExam(String bodyExam) {
		this.bodyExam = bodyExam;
	}

	public String getDiagDesc() {
		return diagDesc;
	}

	public void setDiagDesc(String diagDesc) {
		this.diagDesc = diagDesc;
	}

	public String getTreatment() {
		return treatment;
	}

	public void setTreatment(String treatment) {
		this.treatment = treatment;
	}

	public String getSuggestion() {
		return suggestion;
	}

	public void setSuggestion(String suggestion) {
		this.suggestion = suggestion;
	}

	public String getAdvice() {
		return advice;
	}

	public void setAdvice(String advice) {
		this.advice = advice;
	}

	public String getOperationRecord() {
		return operationRecord;
	}

	public void setOperationRecord(String operationRecord) {
		this.operationRecord = operationRecord;
	}

	public String getMedicalRecord() {
		return medicalRecord;
	}

	public void setMedicalRecord(String medicalRecord) {
		this.medicalRecord = medicalRecord;
	}

	public String getAccExam() {
		return accExam;
	}

	public void setAccExam(String accExam) {
		this.accExam = accExam;
	}


}
