package cn.sportsdata.webapp.youth.common.vo.patient;

import java.io.Serializable;
import java.util.Date;

public class OrdersVO implements Serializable {
	private static final long serialVersionUID = 8628757275474528838L;
	   /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.PATIENT_ID
     *
     * @mbggenerated
     */
    private String patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.VISIT_ID
     *
     * @mbggenerated
     */
    private Integer visitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.ORDER_NO
     *
     * @mbggenerated
     */
    private Integer orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.ORDER_SUB_NO
     *
     * @mbggenerated
     */
    private Integer orderSubNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.REPEAT_INDICATOR
     *
     * @mbggenerated
     */
    private Integer repeatIndicator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.ORDER_CLASS
     *
     * @mbggenerated
     */
    private String orderClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.ORDER_CODE
     *
     * @mbggenerated
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.DOSAGE
     *
     * @mbggenerated
     */
    private Double dosage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.DOSAGE_UNITS
     *
     * @mbggenerated
     */
    private String dosageUnits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.ADMINISTRATION
     *
     * @mbggenerated
     */
    private String administration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.DURATION
     *
     * @mbggenerated
     */
    private Integer duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.DURATION_UNITS
     *
     * @mbggenerated
     */
    private String durationUnits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.START_DATE_TIME
     *
     * @mbggenerated
     */
    private Date startDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.STOP_DATE_TIME
     *
     * @mbggenerated
     */
    private Date stopDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.FREQUENCY
     *
     * @mbggenerated
     */
    private String frequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.FREQ_COUNTER
     *
     * @mbggenerated
     */
    private Integer freqCounter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.FREQ_INTERVAL
     *
     * @mbggenerated
     */
    private Integer freqInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.FREQ_INTERVAL_UNIT
     *
     * @mbggenerated
     */
    private String freqIntervalUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.FREQ_DETAIL
     *
     * @mbggenerated
     */
    private String freqDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.PERFORM_SCHEDULE
     *
     * @mbggenerated
     */
    private String performSchedule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.PERFORM_RESULT
     *
     * @mbggenerated
     */
    private String performResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.ORDERING_DEPT
     *
     * @mbggenerated
     */
    private String orderingDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.DOCTOR
     *
     * @mbggenerated
     */
    private String doctor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.STOP_DOCTOR
     *
     * @mbggenerated
     */
    private String stopDoctor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.NURSE
     *
     * @mbggenerated
     */
    private String nurse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.STOP_NURSE
     *
     * @mbggenerated
     */
    private String stopNurse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.ENTER_DATE_TIME
     *
     * @mbggenerated
     */
    private Date enterDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.STOP_ORDER_DATE_TIME
     *
     * @mbggenerated
     */
    private Date stopOrderDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.ORDER_STATUS
     *
     * @mbggenerated
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.DRUG_BILLING_ATTR
     *
     * @mbggenerated
     */
    private Integer drugBillingAttr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.BILLING_ATTR
     *
     * @mbggenerated
     */
    private Integer billingAttr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.LAST_PERFORM_DATE_TIME
     *
     * @mbggenerated
     */
    private Date lastPerformDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.LAST_ACCTING_DATE_TIME
     *
     * @mbggenerated
     */
    private Date lastAcctingDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.CURRENT_PRESC_NO
     *
     * @mbggenerated
     */
    private Integer currentPrescNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.DOCTOR_USER
     *
     * @mbggenerated
     */
    private String doctorUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.VERIFY_DATA_TIME
     *
     * @mbggenerated
     */
    private Date verifyDataTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.ORDER_VERIFY_USER
     *
     * @mbggenerated
     */
    private String orderVerifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.ORDER_VERIFY_STATUS
     *
     * @mbggenerated
     */
    private String orderVerifyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.ORDER_PRINT_INDICATOR
     *
     * @mbggenerated
     */
    private Integer orderPrintIndicator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.PROCESSING_DATE_TIME
     *
     * @mbggenerated
     */
    private Date processingDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.PROCESSING_NURSE
     *
     * @mbggenerated
     */
    private String processingNurse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.STOP_PROCESSING_NURSE
     *
     * @mbggenerated
     */
    private String stopProcessingNurse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.STOP_PROCESSING_DATE_TIME
     *
     * @mbggenerated
     */
    private Date stopProcessingDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.CANCEL_DATE_TIME
     *
     * @mbggenerated
     */
    private Date cancelDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.CANCEL_DOCTOR
     *
     * @mbggenerated
     */
    private String cancelDoctor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.DEGREE
     *
     * @mbggenerated
     */
    private Integer degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.APP_NO
     *
     * @mbggenerated
     */
    private String appNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.IS_ADJUST
     *
     * @mbggenerated
     */
    private Integer isAdjust;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.CONVERSION_DATE_TIME
     *
     * @mbggenerated
     */
    private Date conversionDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.CONTINUE_ORDER_NO
     *
     * @mbggenerated
     */
    private String continueOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.STOP_FLAG
     *
     * @mbggenerated
     */
    private String stopFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.ADAPT_SYMPTOM_INDICATE
     *
     * @mbggenerated
     */
    private Integer adaptSymptomIndicate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.AUDIT_OPER
     *
     * @mbggenerated
     */
    private String auditOper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.AUDIT_DATE
     *
     * @mbggenerated
     */
    private Date auditDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.AUDIT_FLAG
     *
     * @mbggenerated
     */
    private String auditFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.IS_SELF
     *
     * @mbggenerated
     */
    private String isSelf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.DRUG_PURPOS
     *
     * @mbggenerated
     */
    private String drugPurpos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.LAST_UPDATE
     *
     * @mbggenerated
     */
    private Date lastUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyfsy_his_orders.ORDER_TEXT
     *
     * @mbggenerated
     */
    private String orderText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.PATIENT_ID
     *
     * @return the value of zyfsy_his_orders.PATIENT_ID
     *
     * @mbggenerated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.PATIENT_ID
     *
     * @param patientId the value for zyfsy_his_orders.PATIENT_ID
     *
     * @mbggenerated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.VISIT_ID
     *
     * @return the value of zyfsy_his_orders.VISIT_ID
     *
     * @mbggenerated
     */
    public Integer getVisitId() {
        return visitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.VISIT_ID
     *
     * @param visitId the value for zyfsy_his_orders.VISIT_ID
     *
     * @mbggenerated
     */
    public void setVisitId(Integer visitId) {
        this.visitId = visitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.ORDER_NO
     *
     * @return the value of zyfsy_his_orders.ORDER_NO
     *
     * @mbggenerated
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.ORDER_NO
     *
     * @param orderNo the value for zyfsy_his_orders.ORDER_NO
     *
     * @mbggenerated
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.ORDER_SUB_NO
     *
     * @return the value of zyfsy_his_orders.ORDER_SUB_NO
     *
     * @mbggenerated
     */
    public Integer getOrderSubNo() {
        return orderSubNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.ORDER_SUB_NO
     *
     * @param orderSubNo the value for zyfsy_his_orders.ORDER_SUB_NO
     *
     * @mbggenerated
     */
    public void setOrderSubNo(Integer orderSubNo) {
        this.orderSubNo = orderSubNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.REPEAT_INDICATOR
     *
     * @return the value of zyfsy_his_orders.REPEAT_INDICATOR
     *
     * @mbggenerated
     */
    public Integer getRepeatIndicator() {
        return repeatIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.REPEAT_INDICATOR
     *
     * @param repeatIndicator the value for zyfsy_his_orders.REPEAT_INDICATOR
     *
     * @mbggenerated
     */
    public void setRepeatIndicator(Integer repeatIndicator) {
        this.repeatIndicator = repeatIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.ORDER_CLASS
     *
     * @return the value of zyfsy_his_orders.ORDER_CLASS
     *
     * @mbggenerated
     */
    public String getOrderClass() {
        return orderClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.ORDER_CLASS
     *
     * @param orderClass the value for zyfsy_his_orders.ORDER_CLASS
     *
     * @mbggenerated
     */
    public void setOrderClass(String orderClass) {
        this.orderClass = orderClass == null ? null : orderClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.ORDER_CODE
     *
     * @return the value of zyfsy_his_orders.ORDER_CODE
     *
     * @mbggenerated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.ORDER_CODE
     *
     * @param orderCode the value for zyfsy_his_orders.ORDER_CODE
     *
     * @mbggenerated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.DOSAGE
     *
     * @return the value of zyfsy_his_orders.DOSAGE
     *
     * @mbggenerated
     */
    public Double getDosage() {
        return dosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.DOSAGE
     *
     * @param dosage the value for zyfsy_his_orders.DOSAGE
     *
     * @mbggenerated
     */
    public void setDosage(Double dosage) {
        this.dosage = dosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.DOSAGE_UNITS
     *
     * @return the value of zyfsy_his_orders.DOSAGE_UNITS
     *
     * @mbggenerated
     */
    public String getDosageUnits() {
        return dosageUnits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.DOSAGE_UNITS
     *
     * @param dosageUnits the value for zyfsy_his_orders.DOSAGE_UNITS
     *
     * @mbggenerated
     */
    public void setDosageUnits(String dosageUnits) {
        this.dosageUnits = dosageUnits == null ? null : dosageUnits.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.ADMINISTRATION
     *
     * @return the value of zyfsy_his_orders.ADMINISTRATION
     *
     * @mbggenerated
     */
    public String getAdministration() {
        return administration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.ADMINISTRATION
     *
     * @param administration the value for zyfsy_his_orders.ADMINISTRATION
     *
     * @mbggenerated
     */
    public void setAdministration(String administration) {
        this.administration = administration == null ? null : administration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.DURATION
     *
     * @return the value of zyfsy_his_orders.DURATION
     *
     * @mbggenerated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.DURATION
     *
     * @param duration the value for zyfsy_his_orders.DURATION
     *
     * @mbggenerated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.DURATION_UNITS
     *
     * @return the value of zyfsy_his_orders.DURATION_UNITS
     *
     * @mbggenerated
     */
    public String getDurationUnits() {
        return durationUnits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.DURATION_UNITS
     *
     * @param durationUnits the value for zyfsy_his_orders.DURATION_UNITS
     *
     * @mbggenerated
     */
    public void setDurationUnits(String durationUnits) {
        this.durationUnits = durationUnits == null ? null : durationUnits.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.START_DATE_TIME
     *
     * @return the value of zyfsy_his_orders.START_DATE_TIME
     *
     * @mbggenerated
     */
    public Date getStartDateTime() {
        return startDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.START_DATE_TIME
     *
     * @param startDateTime the value for zyfsy_his_orders.START_DATE_TIME
     *
     * @mbggenerated
     */
    public void setStartDateTime(Date startDateTime) {
        this.startDateTime = startDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.STOP_DATE_TIME
     *
     * @return the value of zyfsy_his_orders.STOP_DATE_TIME
     *
     * @mbggenerated
     */
    public Date getStopDateTime() {
        return stopDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.STOP_DATE_TIME
     *
     * @param stopDateTime the value for zyfsy_his_orders.STOP_DATE_TIME
     *
     * @mbggenerated
     */
    public void setStopDateTime(Date stopDateTime) {
        this.stopDateTime = stopDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.FREQUENCY
     *
     * @return the value of zyfsy_his_orders.FREQUENCY
     *
     * @mbggenerated
     */
    public String getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.FREQUENCY
     *
     * @param frequency the value for zyfsy_his_orders.FREQUENCY
     *
     * @mbggenerated
     */
    public void setFrequency(String frequency) {
        this.frequency = frequency == null ? null : frequency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.FREQ_COUNTER
     *
     * @return the value of zyfsy_his_orders.FREQ_COUNTER
     *
     * @mbggenerated
     */
    public Integer getFreqCounter() {
        return freqCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.FREQ_COUNTER
     *
     * @param freqCounter the value for zyfsy_his_orders.FREQ_COUNTER
     *
     * @mbggenerated
     */
    public void setFreqCounter(Integer freqCounter) {
        this.freqCounter = freqCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.FREQ_INTERVAL
     *
     * @return the value of zyfsy_his_orders.FREQ_INTERVAL
     *
     * @mbggenerated
     */
    public Integer getFreqInterval() {
        return freqInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.FREQ_INTERVAL
     *
     * @param freqInterval the value for zyfsy_his_orders.FREQ_INTERVAL
     *
     * @mbggenerated
     */
    public void setFreqInterval(Integer freqInterval) {
        this.freqInterval = freqInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.FREQ_INTERVAL_UNIT
     *
     * @return the value of zyfsy_his_orders.FREQ_INTERVAL_UNIT
     *
     * @mbggenerated
     */
    public String getFreqIntervalUnit() {
        return freqIntervalUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.FREQ_INTERVAL_UNIT
     *
     * @param freqIntervalUnit the value for zyfsy_his_orders.FREQ_INTERVAL_UNIT
     *
     * @mbggenerated
     */
    public void setFreqIntervalUnit(String freqIntervalUnit) {
        this.freqIntervalUnit = freqIntervalUnit == null ? null : freqIntervalUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.FREQ_DETAIL
     *
     * @return the value of zyfsy_his_orders.FREQ_DETAIL
     *
     * @mbggenerated
     */
    public String getFreqDetail() {
        return freqDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.FREQ_DETAIL
     *
     * @param freqDetail the value for zyfsy_his_orders.FREQ_DETAIL
     *
     * @mbggenerated
     */
    public void setFreqDetail(String freqDetail) {
        this.freqDetail = freqDetail == null ? null : freqDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.PERFORM_SCHEDULE
     *
     * @return the value of zyfsy_his_orders.PERFORM_SCHEDULE
     *
     * @mbggenerated
     */
    public String getPerformSchedule() {
        return performSchedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.PERFORM_SCHEDULE
     *
     * @param performSchedule the value for zyfsy_his_orders.PERFORM_SCHEDULE
     *
     * @mbggenerated
     */
    public void setPerformSchedule(String performSchedule) {
        this.performSchedule = performSchedule == null ? null : performSchedule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.PERFORM_RESULT
     *
     * @return the value of zyfsy_his_orders.PERFORM_RESULT
     *
     * @mbggenerated
     */
    public String getPerformResult() {
        return performResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.PERFORM_RESULT
     *
     * @param performResult the value for zyfsy_his_orders.PERFORM_RESULT
     *
     * @mbggenerated
     */
    public void setPerformResult(String performResult) {
        this.performResult = performResult == null ? null : performResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.ORDERING_DEPT
     *
     * @return the value of zyfsy_his_orders.ORDERING_DEPT
     *
     * @mbggenerated
     */
    public String getOrderingDept() {
        return orderingDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.ORDERING_DEPT
     *
     * @param orderingDept the value for zyfsy_his_orders.ORDERING_DEPT
     *
     * @mbggenerated
     */
    public void setOrderingDept(String orderingDept) {
        this.orderingDept = orderingDept == null ? null : orderingDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.DOCTOR
     *
     * @return the value of zyfsy_his_orders.DOCTOR
     *
     * @mbggenerated
     */
    public String getDoctor() {
        return doctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.DOCTOR
     *
     * @param doctor the value for zyfsy_his_orders.DOCTOR
     *
     * @mbggenerated
     */
    public void setDoctor(String doctor) {
        this.doctor = doctor == null ? null : doctor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.STOP_DOCTOR
     *
     * @return the value of zyfsy_his_orders.STOP_DOCTOR
     *
     * @mbggenerated
     */
    public String getStopDoctor() {
        return stopDoctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.STOP_DOCTOR
     *
     * @param stopDoctor the value for zyfsy_his_orders.STOP_DOCTOR
     *
     * @mbggenerated
     */
    public void setStopDoctor(String stopDoctor) {
        this.stopDoctor = stopDoctor == null ? null : stopDoctor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.NURSE
     *
     * @return the value of zyfsy_his_orders.NURSE
     *
     * @mbggenerated
     */
    public String getNurse() {
        return nurse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.NURSE
     *
     * @param nurse the value for zyfsy_his_orders.NURSE
     *
     * @mbggenerated
     */
    public void setNurse(String nurse) {
        this.nurse = nurse == null ? null : nurse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.STOP_NURSE
     *
     * @return the value of zyfsy_his_orders.STOP_NURSE
     *
     * @mbggenerated
     */
    public String getStopNurse() {
        return stopNurse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.STOP_NURSE
     *
     * @param stopNurse the value for zyfsy_his_orders.STOP_NURSE
     *
     * @mbggenerated
     */
    public void setStopNurse(String stopNurse) {
        this.stopNurse = stopNurse == null ? null : stopNurse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.ENTER_DATE_TIME
     *
     * @return the value of zyfsy_his_orders.ENTER_DATE_TIME
     *
     * @mbggenerated
     */
    public Date getEnterDateTime() {
        return enterDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.ENTER_DATE_TIME
     *
     * @param enterDateTime the value for zyfsy_his_orders.ENTER_DATE_TIME
     *
     * @mbggenerated
     */
    public void setEnterDateTime(Date enterDateTime) {
        this.enterDateTime = enterDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.STOP_ORDER_DATE_TIME
     *
     * @return the value of zyfsy_his_orders.STOP_ORDER_DATE_TIME
     *
     * @mbggenerated
     */
    public Date getStopOrderDateTime() {
        return stopOrderDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.STOP_ORDER_DATE_TIME
     *
     * @param stopOrderDateTime the value for zyfsy_his_orders.STOP_ORDER_DATE_TIME
     *
     * @mbggenerated
     */
    public void setStopOrderDateTime(Date stopOrderDateTime) {
        this.stopOrderDateTime = stopOrderDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.ORDER_STATUS
     *
     * @return the value of zyfsy_his_orders.ORDER_STATUS
     *
     * @mbggenerated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.ORDER_STATUS
     *
     * @param orderStatus the value for zyfsy_his_orders.ORDER_STATUS
     *
     * @mbggenerated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.DRUG_BILLING_ATTR
     *
     * @return the value of zyfsy_his_orders.DRUG_BILLING_ATTR
     *
     * @mbggenerated
     */
    public Integer getDrugBillingAttr() {
        return drugBillingAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.DRUG_BILLING_ATTR
     *
     * @param drugBillingAttr the value for zyfsy_his_orders.DRUG_BILLING_ATTR
     *
     * @mbggenerated
     */
    public void setDrugBillingAttr(Integer drugBillingAttr) {
        this.drugBillingAttr = drugBillingAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.BILLING_ATTR
     *
     * @return the value of zyfsy_his_orders.BILLING_ATTR
     *
     * @mbggenerated
     */
    public Integer getBillingAttr() {
        return billingAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.BILLING_ATTR
     *
     * @param billingAttr the value for zyfsy_his_orders.BILLING_ATTR
     *
     * @mbggenerated
     */
    public void setBillingAttr(Integer billingAttr) {
        this.billingAttr = billingAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.LAST_PERFORM_DATE_TIME
     *
     * @return the value of zyfsy_his_orders.LAST_PERFORM_DATE_TIME
     *
     * @mbggenerated
     */
    public Date getLastPerformDateTime() {
        return lastPerformDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.LAST_PERFORM_DATE_TIME
     *
     * @param lastPerformDateTime the value for zyfsy_his_orders.LAST_PERFORM_DATE_TIME
     *
     * @mbggenerated
     */
    public void setLastPerformDateTime(Date lastPerformDateTime) {
        this.lastPerformDateTime = lastPerformDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.LAST_ACCTING_DATE_TIME
     *
     * @return the value of zyfsy_his_orders.LAST_ACCTING_DATE_TIME
     *
     * @mbggenerated
     */
    public Date getLastAcctingDateTime() {
        return lastAcctingDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.LAST_ACCTING_DATE_TIME
     *
     * @param lastAcctingDateTime the value for zyfsy_his_orders.LAST_ACCTING_DATE_TIME
     *
     * @mbggenerated
     */
    public void setLastAcctingDateTime(Date lastAcctingDateTime) {
        this.lastAcctingDateTime = lastAcctingDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.CURRENT_PRESC_NO
     *
     * @return the value of zyfsy_his_orders.CURRENT_PRESC_NO
     *
     * @mbggenerated
     */
    public Integer getCurrentPrescNo() {
        return currentPrescNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.CURRENT_PRESC_NO
     *
     * @param currentPrescNo the value for zyfsy_his_orders.CURRENT_PRESC_NO
     *
     * @mbggenerated
     */
    public void setCurrentPrescNo(Integer currentPrescNo) {
        this.currentPrescNo = currentPrescNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.DOCTOR_USER
     *
     * @return the value of zyfsy_his_orders.DOCTOR_USER
     *
     * @mbggenerated
     */
    public String getDoctorUser() {
        return doctorUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.DOCTOR_USER
     *
     * @param doctorUser the value for zyfsy_his_orders.DOCTOR_USER
     *
     * @mbggenerated
     */
    public void setDoctorUser(String doctorUser) {
        this.doctorUser = doctorUser == null ? null : doctorUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.VERIFY_DATA_TIME
     *
     * @return the value of zyfsy_his_orders.VERIFY_DATA_TIME
     *
     * @mbggenerated
     */
    public Date getVerifyDataTime() {
        return verifyDataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.VERIFY_DATA_TIME
     *
     * @param verifyDataTime the value for zyfsy_his_orders.VERIFY_DATA_TIME
     *
     * @mbggenerated
     */
    public void setVerifyDataTime(Date verifyDataTime) {
        this.verifyDataTime = verifyDataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.ORDER_VERIFY_USER
     *
     * @return the value of zyfsy_his_orders.ORDER_VERIFY_USER
     *
     * @mbggenerated
     */
    public String getOrderVerifyUser() {
        return orderVerifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.ORDER_VERIFY_USER
     *
     * @param orderVerifyUser the value for zyfsy_his_orders.ORDER_VERIFY_USER
     *
     * @mbggenerated
     */
    public void setOrderVerifyUser(String orderVerifyUser) {
        this.orderVerifyUser = orderVerifyUser == null ? null : orderVerifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.ORDER_VERIFY_STATUS
     *
     * @return the value of zyfsy_his_orders.ORDER_VERIFY_STATUS
     *
     * @mbggenerated
     */
    public String getOrderVerifyStatus() {
        return orderVerifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.ORDER_VERIFY_STATUS
     *
     * @param orderVerifyStatus the value for zyfsy_his_orders.ORDER_VERIFY_STATUS
     *
     * @mbggenerated
     */
    public void setOrderVerifyStatus(String orderVerifyStatus) {
        this.orderVerifyStatus = orderVerifyStatus == null ? null : orderVerifyStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.ORDER_PRINT_INDICATOR
     *
     * @return the value of zyfsy_his_orders.ORDER_PRINT_INDICATOR
     *
     * @mbggenerated
     */
    public Integer getOrderPrintIndicator() {
        return orderPrintIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.ORDER_PRINT_INDICATOR
     *
     * @param orderPrintIndicator the value for zyfsy_his_orders.ORDER_PRINT_INDICATOR
     *
     * @mbggenerated
     */
    public void setOrderPrintIndicator(Integer orderPrintIndicator) {
        this.orderPrintIndicator = orderPrintIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.PROCESSING_DATE_TIME
     *
     * @return the value of zyfsy_his_orders.PROCESSING_DATE_TIME
     *
     * @mbggenerated
     */
    public Date getProcessingDateTime() {
        return processingDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.PROCESSING_DATE_TIME
     *
     * @param processingDateTime the value for zyfsy_his_orders.PROCESSING_DATE_TIME
     *
     * @mbggenerated
     */
    public void setProcessingDateTime(Date processingDateTime) {
        this.processingDateTime = processingDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.PROCESSING_NURSE
     *
     * @return the value of zyfsy_his_orders.PROCESSING_NURSE
     *
     * @mbggenerated
     */
    public String getProcessingNurse() {
        return processingNurse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.PROCESSING_NURSE
     *
     * @param processingNurse the value for zyfsy_his_orders.PROCESSING_NURSE
     *
     * @mbggenerated
     */
    public void setProcessingNurse(String processingNurse) {
        this.processingNurse = processingNurse == null ? null : processingNurse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.STOP_PROCESSING_NURSE
     *
     * @return the value of zyfsy_his_orders.STOP_PROCESSING_NURSE
     *
     * @mbggenerated
     */
    public String getStopProcessingNurse() {
        return stopProcessingNurse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.STOP_PROCESSING_NURSE
     *
     * @param stopProcessingNurse the value for zyfsy_his_orders.STOP_PROCESSING_NURSE
     *
     * @mbggenerated
     */
    public void setStopProcessingNurse(String stopProcessingNurse) {
        this.stopProcessingNurse = stopProcessingNurse == null ? null : stopProcessingNurse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.STOP_PROCESSING_DATE_TIME
     *
     * @return the value of zyfsy_his_orders.STOP_PROCESSING_DATE_TIME
     *
     * @mbggenerated
     */
    public Date getStopProcessingDateTime() {
        return stopProcessingDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.STOP_PROCESSING_DATE_TIME
     *
     * @param stopProcessingDateTime the value for zyfsy_his_orders.STOP_PROCESSING_DATE_TIME
     *
     * @mbggenerated
     */
    public void setStopProcessingDateTime(Date stopProcessingDateTime) {
        this.stopProcessingDateTime = stopProcessingDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.CANCEL_DATE_TIME
     *
     * @return the value of zyfsy_his_orders.CANCEL_DATE_TIME
     *
     * @mbggenerated
     */
    public Date getCancelDateTime() {
        return cancelDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.CANCEL_DATE_TIME
     *
     * @param cancelDateTime the value for zyfsy_his_orders.CANCEL_DATE_TIME
     *
     * @mbggenerated
     */
    public void setCancelDateTime(Date cancelDateTime) {
        this.cancelDateTime = cancelDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.CANCEL_DOCTOR
     *
     * @return the value of zyfsy_his_orders.CANCEL_DOCTOR
     *
     * @mbggenerated
     */
    public String getCancelDoctor() {
        return cancelDoctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.CANCEL_DOCTOR
     *
     * @param cancelDoctor the value for zyfsy_his_orders.CANCEL_DOCTOR
     *
     * @mbggenerated
     */
    public void setCancelDoctor(String cancelDoctor) {
        this.cancelDoctor = cancelDoctor == null ? null : cancelDoctor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.DEGREE
     *
     * @return the value of zyfsy_his_orders.DEGREE
     *
     * @mbggenerated
     */
    public Integer getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.DEGREE
     *
     * @param degree the value for zyfsy_his_orders.DEGREE
     *
     * @mbggenerated
     */
    public void setDegree(Integer degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.APP_NO
     *
     * @return the value of zyfsy_his_orders.APP_NO
     *
     * @mbggenerated
     */
    public String getAppNo() {
        return appNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.APP_NO
     *
     * @param appNo the value for zyfsy_his_orders.APP_NO
     *
     * @mbggenerated
     */
    public void setAppNo(String appNo) {
        this.appNo = appNo == null ? null : appNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.IS_ADJUST
     *
     * @return the value of zyfsy_his_orders.IS_ADJUST
     *
     * @mbggenerated
     */
    public Integer getIsAdjust() {
        return isAdjust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.IS_ADJUST
     *
     * @param isAdjust the value for zyfsy_his_orders.IS_ADJUST
     *
     * @mbggenerated
     */
    public void setIsAdjust(Integer isAdjust) {
        this.isAdjust = isAdjust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.CONVERSION_DATE_TIME
     *
     * @return the value of zyfsy_his_orders.CONVERSION_DATE_TIME
     *
     * @mbggenerated
     */
    public Date getConversionDateTime() {
        return conversionDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.CONVERSION_DATE_TIME
     *
     * @param conversionDateTime the value for zyfsy_his_orders.CONVERSION_DATE_TIME
     *
     * @mbggenerated
     */
    public void setConversionDateTime(Date conversionDateTime) {
        this.conversionDateTime = conversionDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.CONTINUE_ORDER_NO
     *
     * @return the value of zyfsy_his_orders.CONTINUE_ORDER_NO
     *
     * @mbggenerated
     */
    public String getContinueOrderNo() {
        return continueOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.CONTINUE_ORDER_NO
     *
     * @param continueOrderNo the value for zyfsy_his_orders.CONTINUE_ORDER_NO
     *
     * @mbggenerated
     */
    public void setContinueOrderNo(String continueOrderNo) {
        this.continueOrderNo = continueOrderNo == null ? null : continueOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.STOP_FLAG
     *
     * @return the value of zyfsy_his_orders.STOP_FLAG
     *
     * @mbggenerated
     */
    public String getStopFlag() {
        return stopFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.STOP_FLAG
     *
     * @param stopFlag the value for zyfsy_his_orders.STOP_FLAG
     *
     * @mbggenerated
     */
    public void setStopFlag(String stopFlag) {
        this.stopFlag = stopFlag == null ? null : stopFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.ADAPT_SYMPTOM_INDICATE
     *
     * @return the value of zyfsy_his_orders.ADAPT_SYMPTOM_INDICATE
     *
     * @mbggenerated
     */
    public Integer getAdaptSymptomIndicate() {
        return adaptSymptomIndicate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.ADAPT_SYMPTOM_INDICATE
     *
     * @param adaptSymptomIndicate the value for zyfsy_his_orders.ADAPT_SYMPTOM_INDICATE
     *
     * @mbggenerated
     */
    public void setAdaptSymptomIndicate(Integer adaptSymptomIndicate) {
        this.adaptSymptomIndicate = adaptSymptomIndicate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.AUDIT_OPER
     *
     * @return the value of zyfsy_his_orders.AUDIT_OPER
     *
     * @mbggenerated
     */
    public String getAuditOper() {
        return auditOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.AUDIT_OPER
     *
     * @param auditOper the value for zyfsy_his_orders.AUDIT_OPER
     *
     * @mbggenerated
     */
    public void setAuditOper(String auditOper) {
        this.auditOper = auditOper == null ? null : auditOper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.AUDIT_DATE
     *
     * @return the value of zyfsy_his_orders.AUDIT_DATE
     *
     * @mbggenerated
     */
    public Date getAuditDate() {
        return auditDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.AUDIT_DATE
     *
     * @param auditDate the value for zyfsy_his_orders.AUDIT_DATE
     *
     * @mbggenerated
     */
    public void setAuditDate(Date auditDate) {
        this.auditDate = auditDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.AUDIT_FLAG
     *
     * @return the value of zyfsy_his_orders.AUDIT_FLAG
     *
     * @mbggenerated
     */
    public String getAuditFlag() {
        return auditFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.AUDIT_FLAG
     *
     * @param auditFlag the value for zyfsy_his_orders.AUDIT_FLAG
     *
     * @mbggenerated
     */
    public void setAuditFlag(String auditFlag) {
        this.auditFlag = auditFlag == null ? null : auditFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.IS_SELF
     *
     * @return the value of zyfsy_his_orders.IS_SELF
     *
     * @mbggenerated
     */
    public String getIsSelf() {
        return isSelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.IS_SELF
     *
     * @param isSelf the value for zyfsy_his_orders.IS_SELF
     *
     * @mbggenerated
     */
    public void setIsSelf(String isSelf) {
        this.isSelf = isSelf == null ? null : isSelf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.DRUG_PURPOS
     *
     * @return the value of zyfsy_his_orders.DRUG_PURPOS
     *
     * @mbggenerated
     */
    public String getDrugPurpos() {
        return drugPurpos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.DRUG_PURPOS
     *
     * @param drugPurpos the value for zyfsy_his_orders.DRUG_PURPOS
     *
     * @mbggenerated
     */
    public void setDrugPurpos(String drugPurpos) {
        this.drugPurpos = drugPurpos == null ? null : drugPurpos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.STATUS
     *
     * @return the value of zyfsy_his_orders.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.STATUS
     *
     * @param status the value for zyfsy_his_orders.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.LAST_UPDATE
     *
     * @return the value of zyfsy_his_orders.LAST_UPDATE
     *
     * @mbggenerated
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.LAST_UPDATE
     *
     * @param lastUpdate the value for zyfsy_his_orders.LAST_UPDATE
     *
     * @mbggenerated
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyfsy_his_orders.ORDER_TEXT
     *
     * @return the value of zyfsy_his_orders.ORDER_TEXT
     *
     * @mbggenerated
     */
    public String getOrderText() {
        return orderText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyfsy_his_orders.ORDER_TEXT
     *
     * @param orderText the value for zyfsy_his_orders.ORDER_TEXT
     *
     * @mbggenerated
     */
    public void setOrderText(String orderText) {
        this.orderText = orderText == null ? null : orderText.trim();
    }
}
