package cn.sportsdata.webapp.youth.common.vo.patient;

import java.io.Serializable;
import java.util.Date;

public class PatientRegistRecord implements Serializable {
	private static final long serialVersionUID = 8628757275474528838L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.hospital_id
     *
     * @mbggenerated
     */
    private String hospitalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.visit_date
     *
     * @mbggenerated
     */
    private Date visitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.visit_no
     *
     * @mbggenerated
     */
    private Integer visitNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.clinic_label
     *
     * @mbggenerated
     */
    private String clinicLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.visit_time_desc
     *
     * @mbggenerated
     */
    private String visitTimeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.serial_no
     *
     * @mbggenerated
     */
    private Integer serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.patient_id
     *
     * @mbggenerated
     */
    private String patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.name_phonetic
     *
     * @mbggenerated
     */
    private String namePhonetic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.age
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.identity
     *
     * @mbggenerated
     */
    private String identity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.charge_type
     *
     * @mbggenerated
     */
    private String chargeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.insurance_type
     *
     * @mbggenerated
     */
    private String insuranceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.insurance_no
     *
     * @mbggenerated
     */
    private String insuranceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.unit_in_contract
     *
     * @mbggenerated
     */
    private String unitInContract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.clinic_type
     *
     * @mbggenerated
     */
    private String clinicType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.first_visit_indicator
     *
     * @mbggenerated
     */
    private Integer firstVisitIndicator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.visit_dept
     *
     * @mbggenerated
     */
    private String visitDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.visit_special_clinic
     *
     * @mbggenerated
     */
    private String visitSpecialClinic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.doctor
     *
     * @mbggenerated
     */
    private String doctor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.mr_provide_indicator
     *
     * @mbggenerated
     */
    private Integer mrProvideIndicator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.registration_status
     *
     * @mbggenerated
     */
    private Integer registrationStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.registering_date
     *
     * @mbggenerated
     */
    private Date registeringDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.symptom
     *
     * @mbggenerated
     */
    private String symptom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.regist_fee
     *
     * @mbggenerated
     */
    private Integer registFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.clinic_fee
     *
     * @mbggenerated
     */
    private Integer clinicFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.other_fee
     *
     * @mbggenerated
     */
    private Integer otherFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.clinic_charge
     *
     * @mbggenerated
     */
    private Integer clinicCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.operator
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.returned_date
     *
     * @mbggenerated
     */
    private Date returnedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.returned_operator
     *
     * @mbggenerated
     */
    private String returnedOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.mode_code
     *
     * @mbggenerated
     */
    private String modeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.card_name
     *
     * @mbggenerated
     */
    private String cardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.card_no
     *
     * @mbggenerated
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.acct_date_time
     *
     * @mbggenerated
     */
    private Date acctDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.acct_no
     *
     * @mbggenerated
     */
    private String acctNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.pay_way
     *
     * @mbggenerated
     */
    private String payWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.mr_provided_indicator
     *
     * @mbggenerated
     */
    private Integer mrProvidedIndicator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.real_sort
     *
     * @mbggenerated
     */
    private String realSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.invoice_no
     *
     * @mbggenerated
     */
    private String invoiceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.clinic_no
     *
     * @mbggenerated
     */
    private String clinicNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.fund_pay
     *
     * @mbggenerated
     */
    private Integer fundPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.insur_yb_type
     *
     * @mbggenerated
     */
    private String insurYbType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.nh_up_flag
     *
     * @mbggenerated
     */
    private String nhUpFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.yydf
     *
     * @mbggenerated
     */
    private Integer yydf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.nh_clinic_no
     *
     * @mbggenerated
     */
    private String nhClinicNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.flag1
     *
     * @mbggenerated
     */
    private Integer flag1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_regist.last_update
     *
     * @mbggenerated
     */
    private Date lastUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.id
     *
     * @return the value of patient_regist.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.id
     *
     * @param id the value for patient_regist.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.hospital_id
     *
     * @return the value of patient_regist.hospital_id
     *
     * @mbggenerated
     */
    public String getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.hospital_id
     *
     * @param hospitalId the value for patient_regist.hospital_id
     *
     * @mbggenerated
     */
    public void setHospitalId(String hospitalId) {
        this.hospitalId = hospitalId == null ? null : hospitalId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.visit_date
     *
     * @return the value of patient_regist.visit_date
     *
     * @mbggenerated
     */
    public Date getVisitDate() {
        return visitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.visit_date
     *
     * @param visitDate the value for patient_regist.visit_date
     *
     * @mbggenerated
     */
    public void setVisitDate(Date visitDate) {
        this.visitDate = visitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.visit_no
     *
     * @return the value of patient_regist.visit_no
     *
     * @mbggenerated
     */
    public Integer getVisitNo() {
        return visitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.visit_no
     *
     * @param visitNo the value for patient_regist.visit_no
     *
     * @mbggenerated
     */
    public void setVisitNo(Integer visitNo) {
        this.visitNo = visitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.clinic_label
     *
     * @return the value of patient_regist.clinic_label
     *
     * @mbggenerated
     */
    public String getClinicLabel() {
        return clinicLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.clinic_label
     *
     * @param clinicLabel the value for patient_regist.clinic_label
     *
     * @mbggenerated
     */
    public void setClinicLabel(String clinicLabel) {
        this.clinicLabel = clinicLabel == null ? null : clinicLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.visit_time_desc
     *
     * @return the value of patient_regist.visit_time_desc
     *
     * @mbggenerated
     */
    public String getVisitTimeDesc() {
        return visitTimeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.visit_time_desc
     *
     * @param visitTimeDesc the value for patient_regist.visit_time_desc
     *
     * @mbggenerated
     */
    public void setVisitTimeDesc(String visitTimeDesc) {
        this.visitTimeDesc = visitTimeDesc == null ? null : visitTimeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.serial_no
     *
     * @return the value of patient_regist.serial_no
     *
     * @mbggenerated
     */
    public Integer getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.serial_no
     *
     * @param serialNo the value for patient_regist.serial_no
     *
     * @mbggenerated
     */
    public void setSerialNo(Integer serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.patient_id
     *
     * @return the value of patient_regist.patient_id
     *
     * @mbggenerated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.patient_id
     *
     * @param patientId the value for patient_regist.patient_id
     *
     * @mbggenerated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.name
     *
     * @return the value of patient_regist.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.name
     *
     * @param name the value for patient_regist.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.name_phonetic
     *
     * @return the value of patient_regist.name_phonetic
     *
     * @mbggenerated
     */
    public String getNamePhonetic() {
        return namePhonetic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.name_phonetic
     *
     * @param namePhonetic the value for patient_regist.name_phonetic
     *
     * @mbggenerated
     */
    public void setNamePhonetic(String namePhonetic) {
        this.namePhonetic = namePhonetic == null ? null : namePhonetic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.sex
     *
     * @return the value of patient_regist.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.sex
     *
     * @param sex the value for patient_regist.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.age
     *
     * @return the value of patient_regist.age
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.age
     *
     * @param age the value for patient_regist.age
     *
     * @mbggenerated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.identity
     *
     * @return the value of patient_regist.identity
     *
     * @mbggenerated
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.identity
     *
     * @param identity the value for patient_regist.identity
     *
     * @mbggenerated
     */
    public void setIdentity(String identity) {
        this.identity = identity == null ? null : identity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.charge_type
     *
     * @return the value of patient_regist.charge_type
     *
     * @mbggenerated
     */
    public String getChargeType() {
        return chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.charge_type
     *
     * @param chargeType the value for patient_regist.charge_type
     *
     * @mbggenerated
     */
    public void setChargeType(String chargeType) {
        this.chargeType = chargeType == null ? null : chargeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.insurance_type
     *
     * @return the value of patient_regist.insurance_type
     *
     * @mbggenerated
     */
    public String getInsuranceType() {
        return insuranceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.insurance_type
     *
     * @param insuranceType the value for patient_regist.insurance_type
     *
     * @mbggenerated
     */
    public void setInsuranceType(String insuranceType) {
        this.insuranceType = insuranceType == null ? null : insuranceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.insurance_no
     *
     * @return the value of patient_regist.insurance_no
     *
     * @mbggenerated
     */
    public String getInsuranceNo() {
        return insuranceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.insurance_no
     *
     * @param insuranceNo the value for patient_regist.insurance_no
     *
     * @mbggenerated
     */
    public void setInsuranceNo(String insuranceNo) {
        this.insuranceNo = insuranceNo == null ? null : insuranceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.unit_in_contract
     *
     * @return the value of patient_regist.unit_in_contract
     *
     * @mbggenerated
     */
    public String getUnitInContract() {
        return unitInContract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.unit_in_contract
     *
     * @param unitInContract the value for patient_regist.unit_in_contract
     *
     * @mbggenerated
     */
    public void setUnitInContract(String unitInContract) {
        this.unitInContract = unitInContract == null ? null : unitInContract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.clinic_type
     *
     * @return the value of patient_regist.clinic_type
     *
     * @mbggenerated
     */
    public String getClinicType() {
        return clinicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.clinic_type
     *
     * @param clinicType the value for patient_regist.clinic_type
     *
     * @mbggenerated
     */
    public void setClinicType(String clinicType) {
        this.clinicType = clinicType == null ? null : clinicType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.first_visit_indicator
     *
     * @return the value of patient_regist.first_visit_indicator
     *
     * @mbggenerated
     */
    public Integer getFirstVisitIndicator() {
        return firstVisitIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.first_visit_indicator
     *
     * @param firstVisitIndicator the value for patient_regist.first_visit_indicator
     *
     * @mbggenerated
     */
    public void setFirstVisitIndicator(Integer firstVisitIndicator) {
        this.firstVisitIndicator = firstVisitIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.visit_dept
     *
     * @return the value of patient_regist.visit_dept
     *
     * @mbggenerated
     */
    public String getVisitDept() {
        return visitDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.visit_dept
     *
     * @param visitDept the value for patient_regist.visit_dept
     *
     * @mbggenerated
     */
    public void setVisitDept(String visitDept) {
        this.visitDept = visitDept == null ? null : visitDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.visit_special_clinic
     *
     * @return the value of patient_regist.visit_special_clinic
     *
     * @mbggenerated
     */
    public String getVisitSpecialClinic() {
        return visitSpecialClinic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.visit_special_clinic
     *
     * @param visitSpecialClinic the value for patient_regist.visit_special_clinic
     *
     * @mbggenerated
     */
    public void setVisitSpecialClinic(String visitSpecialClinic) {
        this.visitSpecialClinic = visitSpecialClinic == null ? null : visitSpecialClinic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.doctor
     *
     * @return the value of patient_regist.doctor
     *
     * @mbggenerated
     */
    public String getDoctor() {
        return doctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.doctor
     *
     * @param doctor the value for patient_regist.doctor
     *
     * @mbggenerated
     */
    public void setDoctor(String doctor) {
        this.doctor = doctor == null ? null : doctor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.mr_provide_indicator
     *
     * @return the value of patient_regist.mr_provide_indicator
     *
     * @mbggenerated
     */
    public Integer getMrProvideIndicator() {
        return mrProvideIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.mr_provide_indicator
     *
     * @param mrProvideIndicator the value for patient_regist.mr_provide_indicator
     *
     * @mbggenerated
     */
    public void setMrProvideIndicator(Integer mrProvideIndicator) {
        this.mrProvideIndicator = mrProvideIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.registration_status
     *
     * @return the value of patient_regist.registration_status
     *
     * @mbggenerated
     */
    public Integer getRegistrationStatus() {
        return registrationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.registration_status
     *
     * @param registrationStatus the value for patient_regist.registration_status
     *
     * @mbggenerated
     */
    public void setRegistrationStatus(Integer registrationStatus) {
        this.registrationStatus = registrationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.registering_date
     *
     * @return the value of patient_regist.registering_date
     *
     * @mbggenerated
     */
    public Date getRegisteringDate() {
        return registeringDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.registering_date
     *
     * @param registeringDate the value for patient_regist.registering_date
     *
     * @mbggenerated
     */
    public void setRegisteringDate(Date registeringDate) {
        this.registeringDate = registeringDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.symptom
     *
     * @return the value of patient_regist.symptom
     *
     * @mbggenerated
     */
    public String getSymptom() {
        return symptom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.symptom
     *
     * @param symptom the value for patient_regist.symptom
     *
     * @mbggenerated
     */
    public void setSymptom(String symptom) {
        this.symptom = symptom == null ? null : symptom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.regist_fee
     *
     * @return the value of patient_regist.regist_fee
     *
     * @mbggenerated
     */
    public Integer getRegistFee() {
        return registFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.regist_fee
     *
     * @param registFee the value for patient_regist.regist_fee
     *
     * @mbggenerated
     */
    public void setRegistFee(Integer registFee) {
        this.registFee = registFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.clinic_fee
     *
     * @return the value of patient_regist.clinic_fee
     *
     * @mbggenerated
     */
    public Integer getClinicFee() {
        return clinicFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.clinic_fee
     *
     * @param clinicFee the value for patient_regist.clinic_fee
     *
     * @mbggenerated
     */
    public void setClinicFee(Integer clinicFee) {
        this.clinicFee = clinicFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.other_fee
     *
     * @return the value of patient_regist.other_fee
     *
     * @mbggenerated
     */
    public Integer getOtherFee() {
        return otherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.other_fee
     *
     * @param otherFee the value for patient_regist.other_fee
     *
     * @mbggenerated
     */
    public void setOtherFee(Integer otherFee) {
        this.otherFee = otherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.clinic_charge
     *
     * @return the value of patient_regist.clinic_charge
     *
     * @mbggenerated
     */
    public Integer getClinicCharge() {
        return clinicCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.clinic_charge
     *
     * @param clinicCharge the value for patient_regist.clinic_charge
     *
     * @mbggenerated
     */
    public void setClinicCharge(Integer clinicCharge) {
        this.clinicCharge = clinicCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.operator
     *
     * @return the value of patient_regist.operator
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.operator
     *
     * @param operator the value for patient_regist.operator
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.returned_date
     *
     * @return the value of patient_regist.returned_date
     *
     * @mbggenerated
     */
    public Date getReturnedDate() {
        return returnedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.returned_date
     *
     * @param returnedDate the value for patient_regist.returned_date
     *
     * @mbggenerated
     */
    public void setReturnedDate(Date returnedDate) {
        this.returnedDate = returnedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.returned_operator
     *
     * @return the value of patient_regist.returned_operator
     *
     * @mbggenerated
     */
    public String getReturnedOperator() {
        return returnedOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.returned_operator
     *
     * @param returnedOperator the value for patient_regist.returned_operator
     *
     * @mbggenerated
     */
    public void setReturnedOperator(String returnedOperator) {
        this.returnedOperator = returnedOperator == null ? null : returnedOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.mode_code
     *
     * @return the value of patient_regist.mode_code
     *
     * @mbggenerated
     */
    public String getModeCode() {
        return modeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.mode_code
     *
     * @param modeCode the value for patient_regist.mode_code
     *
     * @mbggenerated
     */
    public void setModeCode(String modeCode) {
        this.modeCode = modeCode == null ? null : modeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.card_name
     *
     * @return the value of patient_regist.card_name
     *
     * @mbggenerated
     */
    public String getCardName() {
        return cardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.card_name
     *
     * @param cardName the value for patient_regist.card_name
     *
     * @mbggenerated
     */
    public void setCardName(String cardName) {
        this.cardName = cardName == null ? null : cardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.card_no
     *
     * @return the value of patient_regist.card_no
     *
     * @mbggenerated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.card_no
     *
     * @param cardNo the value for patient_regist.card_no
     *
     * @mbggenerated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.acct_date_time
     *
     * @return the value of patient_regist.acct_date_time
     *
     * @mbggenerated
     */
    public Date getAcctDateTime() {
        return acctDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.acct_date_time
     *
     * @param acctDateTime the value for patient_regist.acct_date_time
     *
     * @mbggenerated
     */
    public void setAcctDateTime(Date acctDateTime) {
        this.acctDateTime = acctDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.acct_no
     *
     * @return the value of patient_regist.acct_no
     *
     * @mbggenerated
     */
    public String getAcctNo() {
        return acctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.acct_no
     *
     * @param acctNo the value for patient_regist.acct_no
     *
     * @mbggenerated
     */
    public void setAcctNo(String acctNo) {
        this.acctNo = acctNo == null ? null : acctNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.pay_way
     *
     * @return the value of patient_regist.pay_way
     *
     * @mbggenerated
     */
    public String getPayWay() {
        return payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.pay_way
     *
     * @param payWay the value for patient_regist.pay_way
     *
     * @mbggenerated
     */
    public void setPayWay(String payWay) {
        this.payWay = payWay == null ? null : payWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.mr_provided_indicator
     *
     * @return the value of patient_regist.mr_provided_indicator
     *
     * @mbggenerated
     */
    public Integer getMrProvidedIndicator() {
        return mrProvidedIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.mr_provided_indicator
     *
     * @param mrProvidedIndicator the value for patient_regist.mr_provided_indicator
     *
     * @mbggenerated
     */
    public void setMrProvidedIndicator(Integer mrProvidedIndicator) {
        this.mrProvidedIndicator = mrProvidedIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.real_sort
     *
     * @return the value of patient_regist.real_sort
     *
     * @mbggenerated
     */
    public String getRealSort() {
        return realSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.real_sort
     *
     * @param realSort the value for patient_regist.real_sort
     *
     * @mbggenerated
     */
    public void setRealSort(String realSort) {
        this.realSort = realSort == null ? null : realSort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.invoice_no
     *
     * @return the value of patient_regist.invoice_no
     *
     * @mbggenerated
     */
    public String getInvoiceNo() {
        return invoiceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.invoice_no
     *
     * @param invoiceNo the value for patient_regist.invoice_no
     *
     * @mbggenerated
     */
    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo == null ? null : invoiceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.clinic_no
     *
     * @return the value of patient_regist.clinic_no
     *
     * @mbggenerated
     */
    public String getClinicNo() {
        return clinicNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.clinic_no
     *
     * @param clinicNo the value for patient_regist.clinic_no
     *
     * @mbggenerated
     */
    public void setClinicNo(String clinicNo) {
        this.clinicNo = clinicNo == null ? null : clinicNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.fund_pay
     *
     * @return the value of patient_regist.fund_pay
     *
     * @mbggenerated
     */
    public Integer getFundPay() {
        return fundPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.fund_pay
     *
     * @param fundPay the value for patient_regist.fund_pay
     *
     * @mbggenerated
     */
    public void setFundPay(Integer fundPay) {
        this.fundPay = fundPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.insur_yb_type
     *
     * @return the value of patient_regist.insur_yb_type
     *
     * @mbggenerated
     */
    public String getInsurYbType() {
        return insurYbType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.insur_yb_type
     *
     * @param insurYbType the value for patient_regist.insur_yb_type
     *
     * @mbggenerated
     */
    public void setInsurYbType(String insurYbType) {
        this.insurYbType = insurYbType == null ? null : insurYbType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.nh_up_flag
     *
     * @return the value of patient_regist.nh_up_flag
     *
     * @mbggenerated
     */
    public String getNhUpFlag() {
        return nhUpFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.nh_up_flag
     *
     * @param nhUpFlag the value for patient_regist.nh_up_flag
     *
     * @mbggenerated
     */
    public void setNhUpFlag(String nhUpFlag) {
        this.nhUpFlag = nhUpFlag == null ? null : nhUpFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.yydf
     *
     * @return the value of patient_regist.yydf
     *
     * @mbggenerated
     */
    public Integer getYydf() {
        return yydf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.yydf
     *
     * @param yydf the value for patient_regist.yydf
     *
     * @mbggenerated
     */
    public void setYydf(Integer yydf) {
        this.yydf = yydf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.flag
     *
     * @return the value of patient_regist.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.flag
     *
     * @param flag the value for patient_regist.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.nh_clinic_no
     *
     * @return the value of patient_regist.nh_clinic_no
     *
     * @mbggenerated
     */
    public String getNhClinicNo() {
        return nhClinicNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.nh_clinic_no
     *
     * @param nhClinicNo the value for patient_regist.nh_clinic_no
     *
     * @mbggenerated
     */
    public void setNhClinicNo(String nhClinicNo) {
        this.nhClinicNo = nhClinicNo == null ? null : nhClinicNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.flag1
     *
     * @return the value of patient_regist.flag1
     *
     * @mbggenerated
     */
    public Integer getFlag1() {
        return flag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.flag1
     *
     * @param flag1 the value for patient_regist.flag1
     *
     * @mbggenerated
     */
    public void setFlag1(Integer flag1) {
        this.flag1 = flag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.status
     *
     * @return the value of patient_regist.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.status
     *
     * @param status the value for patient_regist.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.created_time
     *
     * @return the value of patient_regist.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.created_time
     *
     * @param createdTime the value for patient_regist.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_regist.last_update
     *
     * @return the value of patient_regist.last_update
     *
     * @mbggenerated
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_regist.last_update
     *
     * @param lastUpdate the value for patient_regist.last_update
     *
     * @mbggenerated
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
}
