package cn.sportsdata.webapp.youth.common.vo.patient;

import java.io.Serializable;
import java.util.Date;

public class ResidentRecord implements Serializable {
	public static final long RESIDENT_DOCTOR = 0x0001;
	public static final long DIRECTOR_DOCTOR = 0x0002;
	public static final long ATTENDING_DOCTOR = 0x0004;
	
	private static final long serialVersionUID = 8628757275474528838L;
	
	private String doctorInCharge;
	
	  public String getDoctorInCharge() {
		return doctorInCharge;
	}

	public void setDoctorInCharge(String doctorInCharge) {
		this.doctorInCharge = doctorInCharge;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.hospital_id
     *
     * @mbggenerated
     */
    private String hospitalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.patient_id
     *
     * @mbggenerated
     */
    private String patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.doctor_id
     *
     * @mbggenerated
     */
    private String doctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.last_update
     *
     * @mbggenerated
     */
    private Date lastUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.department_id
     *
     * @mbggenerated
     */
    private String departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.ADMISSION_NUMBER
     *
     * @mbggenerated
     */
    private String admissionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.GENDER
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.AGE
     *
     * @mbggenerated
     */
    private Double age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.FEE_TYPE
     *
     * @mbggenerated
     */
    private String feeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.PATIENTS_SECTION_CODE
     *
     * @mbggenerated
     */
    private String patientsSectionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.DISCHARGE_DATE_TIME
     *
     * @mbggenerated
     */
    private Date dischargeDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.IN_OUT_STATUS
     *
     * @mbggenerated
     */
    private Double inOutStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.HOSPITAL_BEDS
     *
     * @mbggenerated
     */
    private Integer hospitalBeds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.ADMISSION_DATE
     *
     * @mbggenerated
     */
    private Date admissionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.SECTION_DATE
     *
     * @mbggenerated
     */
    private Date sectionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.DIAGNOSE
     *
     * @mbggenerated
     */
    private String diagnose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.NURSE_LEVEL
     *
     * @mbggenerated
     */
    private String nurseLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.CRITICAL_LEVEL
     *
     * @mbggenerated
     */
    private String criticalLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.RESIDENT_ID
     *
     * @mbggenerated
     */
    private String residentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.DIRECTOR
     *
     * @mbggenerated
     */
    private String director;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.ATTENDING_DOCTOR
     *
     * @mbggenerated
     */
    private String attendingDoctor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resident_record.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.id
     *
     * @return the value of resident_record.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.id
     *
     * @param id the value for resident_record.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.hospital_id
     *
     * @return the value of resident_record.hospital_id
     *
     * @mbggenerated
     */
    public String getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.hospital_id
     *
     * @param hospitalId the value for resident_record.hospital_id
     *
     * @mbggenerated
     */
    public void setHospitalId(String hospitalId) {
        this.hospitalId = hospitalId == null ? null : hospitalId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.patient_id
     *
     * @return the value of resident_record.patient_id
     *
     * @mbggenerated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.patient_id
     *
     * @param patientId the value for resident_record.patient_id
     *
     * @mbggenerated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.doctor_id
     *
     * @return the value of resident_record.doctor_id
     *
     * @mbggenerated
     */
    public String getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.doctor_id
     *
     * @param doctorId the value for resident_record.doctor_id
     *
     * @mbggenerated
     */
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId == null ? null : doctorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.type
     *
     * @return the value of resident_record.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.type
     *
     * @param type the value for resident_record.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.create_time
     *
     * @return the value of resident_record.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.create_time
     *
     * @param createTime the value for resident_record.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.last_update
     *
     * @return the value of resident_record.last_update
     *
     * @mbggenerated
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.last_update
     *
     * @param lastUpdate the value for resident_record.last_update
     *
     * @mbggenerated
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.status
     *
     * @return the value of resident_record.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.status
     *
     * @param status the value for resident_record.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.start_time
     *
     * @return the value of resident_record.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.start_time
     *
     * @param startTime the value for resident_record.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.end_time
     *
     * @return the value of resident_record.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.end_time
     *
     * @param endTime the value for resident_record.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.department_id
     *
     * @return the value of resident_record.department_id
     *
     * @mbggenerated
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.department_id
     *
     * @param departmentId the value for resident_record.department_id
     *
     * @mbggenerated
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.NAME
     *
     * @return the value of resident_record.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.NAME
     *
     * @param name the value for resident_record.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.ADMISSION_NUMBER
     *
     * @return the value of resident_record.ADMISSION_NUMBER
     *
     * @mbggenerated
     */
    public String getAdmissionNumber() {
        return admissionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.ADMISSION_NUMBER
     *
     * @param admissionNumber the value for resident_record.ADMISSION_NUMBER
     *
     * @mbggenerated
     */
    public void setAdmissionNumber(String admissionNumber) {
        this.admissionNumber = admissionNumber == null ? null : admissionNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.GENDER
     *
     * @return the value of resident_record.GENDER
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.GENDER
     *
     * @param gender the value for resident_record.GENDER
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.AGE
     *
     * @return the value of resident_record.AGE
     *
     * @mbggenerated
     */
    public Double getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.AGE
     *
     * @param age the value for resident_record.AGE
     *
     * @mbggenerated
     */
    public void setAge(Double age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.FEE_TYPE
     *
     * @return the value of resident_record.FEE_TYPE
     *
     * @mbggenerated
     */
    public String getFeeType() {
        return feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.FEE_TYPE
     *
     * @param feeType the value for resident_record.FEE_TYPE
     *
     * @mbggenerated
     */
    public void setFeeType(String feeType) {
        this.feeType = feeType == null ? null : feeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.PATIENTS_SECTION_CODE
     *
     * @return the value of resident_record.PATIENTS_SECTION_CODE
     *
     * @mbggenerated
     */
    public String getPatientsSectionCode() {
        return patientsSectionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.PATIENTS_SECTION_CODE
     *
     * @param patientsSectionCode the value for resident_record.PATIENTS_SECTION_CODE
     *
     * @mbggenerated
     */
    public void setPatientsSectionCode(String patientsSectionCode) {
        this.patientsSectionCode = patientsSectionCode == null ? null : patientsSectionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.DISCHARGE_DATE_TIME
     *
     * @return the value of resident_record.DISCHARGE_DATE_TIME
     *
     * @mbggenerated
     */
    public Date getDischargeDateTime() {
        return dischargeDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.DISCHARGE_DATE_TIME
     *
     * @param dischargeDateTime the value for resident_record.DISCHARGE_DATE_TIME
     *
     * @mbggenerated
     */
    public void setDischargeDateTime(Date dischargeDateTime) {
        this.dischargeDateTime = dischargeDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.IN_OUT_STATUS
     *
     * @return the value of resident_record.IN_OUT_STATUS
     *
     * @mbggenerated
     */
    public Double getInOutStatus() {
        return inOutStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.IN_OUT_STATUS
     *
     * @param inOutStatus the value for resident_record.IN_OUT_STATUS
     *
     * @mbggenerated
     */
    public void setInOutStatus(Double inOutStatus) {
        this.inOutStatus = inOutStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.HOSPITAL_BEDS
     *
     * @return the value of resident_record.HOSPITAL_BEDS
     *
     * @mbggenerated
     */
    public Integer getHospitalBeds() {
        return hospitalBeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.HOSPITAL_BEDS
     *
     * @param hospitalBeds the value for resident_record.HOSPITAL_BEDS
     *
     * @mbggenerated
     */
    public void setHospitalBeds(Integer hospitalBeds) {
        this.hospitalBeds = hospitalBeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.ADMISSION_DATE
     *
     * @return the value of resident_record.ADMISSION_DATE
     *
     * @mbggenerated
     */
    public Date getAdmissionDate() {
        return admissionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.ADMISSION_DATE
     *
     * @param admissionDate the value for resident_record.ADMISSION_DATE
     *
     * @mbggenerated
     */
    public void setAdmissionDate(Date admissionDate) {
        this.admissionDate = admissionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.SECTION_DATE
     *
     * @return the value of resident_record.SECTION_DATE
     *
     * @mbggenerated
     */
    public Date getSectionDate() {
        return sectionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.SECTION_DATE
     *
     * @param sectionDate the value for resident_record.SECTION_DATE
     *
     * @mbggenerated
     */
    public void setSectionDate(Date sectionDate) {
        this.sectionDate = sectionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.DIAGNOSE
     *
     * @return the value of resident_record.DIAGNOSE
     *
     * @mbggenerated
     */
    public String getDiagnose() {
        return diagnose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.DIAGNOSE
     *
     * @param diagnose the value for resident_record.DIAGNOSE
     *
     * @mbggenerated
     */
    public void setDiagnose(String diagnose) {
        this.diagnose = diagnose == null ? null : diagnose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.NURSE_LEVEL
     *
     * @return the value of resident_record.NURSE_LEVEL
     *
     * @mbggenerated
     */
    public String getNurseLevel() {
        return nurseLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.NURSE_LEVEL
     *
     * @param nurseLevel the value for resident_record.NURSE_LEVEL
     *
     * @mbggenerated
     */
    public void setNurseLevel(String nurseLevel) {
        this.nurseLevel = nurseLevel == null ? null : nurseLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.CRITICAL_LEVEL
     *
     * @return the value of resident_record.CRITICAL_LEVEL
     *
     * @mbggenerated
     */
    public String getCriticalLevel() {
        return criticalLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.CRITICAL_LEVEL
     *
     * @param criticalLevel the value for resident_record.CRITICAL_LEVEL
     *
     * @mbggenerated
     */
    public void setCriticalLevel(String criticalLevel) {
        this.criticalLevel = criticalLevel == null ? null : criticalLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.RESIDENT_ID
     *
     * @return the value of resident_record.RESIDENT_ID
     *
     * @mbggenerated
     */
    public String getResidentId() {
        return residentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.RESIDENT_ID
     *
     * @param residentId the value for resident_record.RESIDENT_ID
     *
     * @mbggenerated
     */
    public void setResidentId(String residentId) {
        this.residentId = residentId == null ? null : residentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.DIRECTOR
     *
     * @return the value of resident_record.DIRECTOR
     *
     * @mbggenerated
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.DIRECTOR
     *
     * @param director the value for resident_record.DIRECTOR
     *
     * @mbggenerated
     */
    public void setDirector(String director) {
        this.director = director == null ? null : director.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.ATTENDING_DOCTOR
     *
     * @return the value of resident_record.ATTENDING_DOCTOR
     *
     * @mbggenerated
     */
    public String getAttendingDoctor() {
        return attendingDoctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.ATTENDING_DOCTOR
     *
     * @param attendingDoctor the value for resident_record.ATTENDING_DOCTOR
     *
     * @mbggenerated
     */
    public void setAttendingDoctor(String attendingDoctor) {
        this.attendingDoctor = attendingDoctor == null ? null : attendingDoctor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resident_record.UPDATE_DATE
     *
     * @return the value of resident_record.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resident_record.UPDATE_DATE
     *
     * @param updateDate the value for resident_record.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}
